apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookstore-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "bookstore-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "bookstore-api.name" . }}
    spec:
      containers:
        - name: bookstore-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
            - name: APP_ENV
              value: {{ .Values.env.APP_ENV | quote }}
